version: "3.8"

services:
  app:
    build: .
    container_name: bookstore-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=OnlineBookStoreDB
    volumes:
      - .:/app
    command: npm start

  db:
    image: postgres:latest
    container_name: bookstore-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: OnlineBookStoreDB

volumes:
  postgres-data:
